### ISSUE TITLE
Flash Messages

### ISSUE THREAD

**Issue by paulinhowoox** [alxbbarbosa/LittleBoy#3]
Não estou conseguindo gerar mensagens de sucesso, mas as de erro sim, como do exemplo do formulario.
Alguém ja conseguiu usar?

**Comment by alxbbarbosa** [comment]
Olá Paulinho está retornando alguma mensagem de erro?

**Comment by paulinhowoox** [comment]
Nenhuma mensagem de erro. Aqui está o codigo que fiz no controller.
`session()->flash('success', 'Balão cadastrado com sucesso.');
  return response()->redirect(route('manager.balloon.index'));`

E na view:
`@if ($message = session()->has('success'))
       <div class="alert alert-success">
               <strong>{{ $message }}</strong>
       </div>
@endif`

Já tentei com has e get mas mesmo assim não exibe, só exibe os erros.

**Comment by alxbbarbosa** [comment]
Ok,
session()->has('variavel') retorna um boolean e o get retorna a variável da sessão. Você precisa usar os dois ou nessa sua linha de raciocínio, fazer assim:

```
@if (($message = session()->get('variavel')) != null)
````
Mas essa é uma prática não utilizada nos ambientes de desenvolvimento hoje em dia por conta da questão de clareza do código. Se você está programando só para você tranquilo, mas as equipes de desenvolvimento não estão aceitando mais.

Então você precisa usar um no if fará verificar se tem valor:
```
@if (session()->has('variavel'))
    ....
@endif
```

E precisa usar o outro para recuperar o valor:
```
{{ session()->get('variavel') }}
```

Daí ficaria assim, como você já deve estar imaginando:
```
@if (session()->has('success'))
    <div class="alert alert-success"> <strong>{{ session()->get('success') }}</strong>
@endif
```

Se você já tentou desta maneira e não deu certo, se desejar compartilhar o seu código ... você subiu no github?

**Comment by alxbbarbosa** [comment]
Conseguiu? Posso fechar a Issue?

**Comment by paulinhowoox** [comment]
Consegui não! Vou subir o code no github e te mandar o link

**Comment by paulinhowoox** [comment]
@alxbbarbosa consegui resolver, fiz o commit numa branch separada pra você dar uma olhada. Obrigado pela ajuda.

**Comment by alxbbarbosa** [comment]
Show! Vou dar uma olhada! Se você desejar, toca esse projeto adiante! Daí você vai curtir os próximos. Tenho uma versão aprimorada desse com twig que gera formulários automaticamente e inclusive integrado a um carinho de compras. Vou me esforçar em adicionar algum deles aí pra você conhecer e mais outros que você quiser compartilhar.

**Comment by paulinhowoox** [comment]
Opa! Eu usei o LitteBoy num projeto de um cliente aqui. Eu adicionei o
Blade do laravel nele e o eloquent e tá uma belezinha. Eu tô largando um
pouco os frameworks e voltando pro PHP puro e o LitteBoy me deu um norte
que eu não tive até hoje. Se tiver um outro projeto eu quero conhecer sim,
tenho muito interesse.

Em sex, 10 de jul de 2020 22:55, Alexandre Bezerra Barbosa <
notifications@github.com> escreveu:
